import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  devsSidebar: [{type: 'autogenerated', dirName: 'dev-guide'}],
  opsSidebar: [{type: 'autogenerated', dirName: 'ops-guide'}],
  communitySidebar: [{type: 'autogenerated', dirName: 'drand-community'}],
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
  conceptsSidebar: [{type: 'autogenerated', dirName: 'concepts'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'drand-faq'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
